//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Generos
    {
        public Generos()
        {
            this.Peliculas = new HashSet<Peliculas>();
        }

        [Required]
        public int IdGenero { get; set; }

        [Required]
        public string Nombre { get; set; }
    
        public virtual ICollection<Peliculas> Peliculas { get; set; }
    }
}
