//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Peliculas
    {
        public Peliculas()
        {
            this.Carteleras = new HashSet<Carteleras>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int IdPelicula { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Descripcion { get; set; }
        [Required]
        public string Imagen { get; set; }
        [Required(ErrorMessage = "El campo calificación es obligatorio")] 
        public int IdCalificacion { get; set; }
        [Required(ErrorMessage = "El campo Género es obligatorio")]
        public int IdGenero { get; set; }
        [Required]
        public int Duracion { get; set; }

        [Required]
        public HttpPostedFileBase ArchivoImagen { get; set; }

        public System.DateTime FechaCarga { get; set; }
    
        public virtual Calificaciones Calificaciones { get; set; }
        public virtual ICollection<Carteleras> Carteleras { get; set; }
        public virtual Generos Generos { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
