//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peliculas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        [Required(ErrorMessage = "Ingrese su nombre de usuario")]
        public string NombreUsuario { get; set; }
        [Required(ErrorMessage = "Ingrese su contraseña")]
        public string Password { get; set; }
    }
}
